# Generated by Django 4.2.5 on 2023-12-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_anime_episodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntuacion',
            name='user',
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
